version: "2.4"
services:
    db:
      container_name: python_skillup_dev-db
      image: mysql:8.0.18
      volumes:
        - ./data/mysql-dev:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
        interval: 10s
        timeout: 10s
        retries: 5
      command: --default-authentication-plugin=mysql_native_password
    phpmyadmin:
      container_name: python_skillup_dev-phpmyadmin
      image: phpmyadmin/phpmyadmin:4.9
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      depends_on:
        - db
      ports:
        - "8087:80"
    web:
      container_name: python_skillup_dev-server
      build: ./config/dev
      command: python3 manage.py runserver 0.0.0.0:8000
      environment:
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
      volumes:
        - ./code:/code
      ports:
        - "8088:8000"
      depends_on:
        db:
          condition: service_healthy